import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../components/Banner'
import { Header } from '../components/Header'
import { NewsItem } from '../components/NewsItem'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Banner banners={['/assets/banner01.jpg', '/assets/rena-4th.jpg', '/assets/cool.jpg']} />
            <main className={styles.mainArea}>
                <div className={styles.newsAndUpdates}>
                    <div className={styles.label}>NEWS & UPDATES</div>
                    <div className={styles.mainNewsAndUpdates}>
                        <div className={styles.announcements}>
                            <div>ANNOUNCEMENTS</div>
                            <div className={styles.news}>
                                <NewsItem type='Event' title='2022 Summer Special Events' />
                                <NewsItem type='Item Mall' title='New Noah IB: Nereid + Nereid Eye' />
                                <NewsItem type='Notice' title='August 24th Patch Notes' />
                                <NewsItem type='Notice' title=' [Announcement] Dungeon Bug Fixed' />
                                <NewsItem type='Event' title='Weekend Event 2' />
                                <NewsItem type='Event' title='Class Change Chance! Event' />
                                <NewsItem type='Item Mall' title='Costume Premium Package Resale' />
                            </div>
                        </div>
                        <div className={styles.news}></div>
                        <div className={styles.guides}></div>
                    </div>
                </div>
            </main>

            <div className={styles.background} />
        </div>
    )
}

export default Home
